// This file was autogenerated by ../../library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../apps/pstj/demos/material/button.js', ['pstj.demos.button'], ['goog.array', 'goog.events', 'goog.ui.Component.EventType', 'goog.ui.decorate', 'pstj.material.Button'], false);
goog.addDependency('../../../apps/pstj/demos/material/checkbox.js', ['pstj.demos.checkbox'], ['goog.array', 'goog.ui.decorate', 'pstj.material.Checkbox'], false);
goog.addDependency('../../../apps/pstj/demos/material/drawerpanel.js', ['pstj.demos.drawerpanel'], ['pstj.material.DrawerPanel'], false);
goog.addDependency('../../../apps/pstj/demos/material/element.js', ['pstj.demos.element'], ['pstj.material.Element'], false);
goog.addDependency('../../../apps/pstj/demos/material/headerpanel.js', ['pstj.demos.headerpanel'], ['goog.ui.decorate', 'pstj.material.HeaderPanel'], false);
goog.addDependency('../../../apps/pstj/demos/material/iconcontainer.js', ['pstj.demos.iconcontainer'], ['goog.ui.decorate', 'pstj.material.IconContainer'], false);
goog.addDependency('../../../apps/pstj/demos/material/input.js', ['pstj.demos.input'], ['pstj.material.InputElement'], false);
goog.addDependency('../../../apps/pstj/demos/material/materialinput.js', ['pstj.demos.materialinput'], ['pstj.material.MaterialInput'], false);
goog.addDependency('../../../apps/pstj/demos/material/panel.js', ['pstj.demos.panel'], ['pstj.material.Panel'], false);
goog.addDependency('../../../apps/pstj/demos/material/progressbar.js', ['pstj.demos.progressbar'], ['pstj.material.Progressbar'], false);
goog.addDependency('../../../apps/pstj/demos/material/radiobutton.js', ['pstj.demos.radiobutton'], ['goog.array', 'goog.ui.decorate', 'pstj.material.RadioButton'], false);
goog.addDependency('../../../apps/pstj/demos/material/radiogroup.js', ['pstj.demos.radiogroup'], ['goog.ui.decorate', 'pstj.material.RadioGroup'], false);
goog.addDependency('../../../apps/pstj/demos/material/ripple.js', ['pstj.demos.ripple'], ['goog.ui.decorate', 'pstj.material.Element', 'pstj.material.EventMap', 'pstj.material.Ripple'], false);
goog.addDependency('../../../apps/pstj/demos/material/shadow.js', ['pstj.demos.shadow'], ['pstj.material.Element', 'pstj.material.Shadow'], false);
goog.addDependency('../../../apps/pstj/demos/material/togglebutton.js', ['pstj.demos.togglebutton'], ['goog.array', 'goog.ui.decorate', 'pstj.material.ToggleButton'], false);
goog.addDependency('../../../apps/pstj/demos/navigation/navigation.js', ['pstj.demos.navigation'], ['goog.dom', 'goog.ui.tree.TreeControl', 'pstj.demos.navigationdata'], false);
goog.addDependency('../../../apps/pstj/demos/navigation/navigationdata.js', ['pstj.demos.navigationdata'], [], false);
goog.addDependency('../../../apps/pstj/demos/tableview/tableview.js', ['pstj.demos.tableview'], ['goog.dom', 'pstj.ds.List', 'pstj.ui.TableView'], false);
goog.addDependency('../../../apps/pstj/tpl/icons.soy.js', ['pstj.material.icons'], ['soy', 'soydata'], false);
goog.addDependency('../../../apps/pstj/tpl/material.soy.js', ['pstj.material.template'], ['goog.asserts', 'soy', 'soydata'], false);
goog.addDependency('../../../apps/pstj/tpl/pstj.soy.js', ['pstj.templates'], ['soy', 'soydata'], false);
goog.addDependency('../../../apps/pstj/tpl/select.soy.js', ['pstj.select'], ['soy', 'soydata'], false);
