// This file was automatically generated by the Soy compiler.
// Please don't edit this file by hand.
// source: templates/ds.soy

/**
 * @fileoverview Templates in namespace pstj.ds.template.
 * @public
 */

goog.provide('pstj.ds.template');

goog.require('goog.soy.data.UnsanitizedText');
goog.require('soy');
goog.require('soy.asserts');
goog.require('soydata');
goog.require('soydata.VERY_UNSAFE');


/**
 * @param {pstj.ds.template.IconRenderer.Params} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.ds.template.IconRenderer = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  /** @type {!goog.soy.data.UnsanitizedText|string} */
  var className = soy.asserts.assertType(goog.isString(opt_data.className) || opt_data.className instanceof goog.soy.data.UnsanitizedText, 'className', opt_data.className, '!goog.soy.data.UnsanitizedText|string');
  /** @type {!goog.soy.data.UnsanitizedText|string} */
  var iconName = soy.asserts.assertType(goog.isString(opt_data.iconName) || opt_data.iconName instanceof goog.soy.data.UnsanitizedText, 'iconName', opt_data.iconName, '!goog.soy.data.UnsanitizedText|string');
  /** @type {!Array<!goog.soy.data.UnsanitizedText|string>} */
  var icons = soy.asserts.assertType(goog.isArray(opt_data.icons), 'icons', opt_data.icons, '!Array<!goog.soy.data.UnsanitizedText|string>');
  var output = '\n// File auto-generated, please do not edit\ngoog.provide(\'pstj.autogen.iconrenderer.' + soy.$$escapeHtml(className) + '\');\n\ngoog.require(\'pstj.autogen.template.icons\');\ngoog.require(\'pstj.material.IconRenderer\');\ngoog.require(\'pstj.material.icons.registry\');\n\ngoog.scope(function() {\nvar IR = pstj.material.IconRenderer;\nvar registry = pstj.material.icons.registry;\n\n\n/** Renderer for \'' + soy.$$escapeHtml(iconName) + '\' icon */\npstj.autogen.iconrenderer.' + soy.$$escapeHtml(className) + ' = goog.defineClass(IR, {\n  constructor: function() {\n    IR.call(this);\n  },\n\n  /** @inheritDoc */\n  getTemplate: function(model) {\n    return pstj.autogen.template.icons.' + soy.$$escapeHtml(className) + '(model);\n  }\n});\ngoog.addSingletonGetter(icons.' + soy.$$escapeHtml(className) + ');\n\n\n// Register the renderer for icon name\n';
  var iconname14List = icons;
  var iconname14ListLen = iconname14List.length;
  for (var iconname14Index = 0; iconname14Index < iconname14ListLen; iconname14Index++) {
    var iconname14Data = iconname14List[iconname14Index];
    output += 'registry.setRenderer(\'' + soy.$$escapeHtml(iconname14Data) + '\', icons.' + soy.$$escapeHtml(className) + '.getInstance());\n';
  }
  output += '\n});  // goog.scope\n\n';
  return soydata.VERY_UNSAFE.ordainSanitizedHtml(output);
};
/**
 * @typedef {{
 *  className: (!goog.soy.data.UnsanitizedText|string),
 *  iconName: (!goog.soy.data.UnsanitizedText|string),
 *  icons: !Array<!goog.soy.data.UnsanitizedText|string>,
 * }}
 */
pstj.ds.template.IconRenderer.Params;
if (goog.DEBUG) {
  pstj.ds.template.IconRenderer.soyTemplateName = 'pstj.ds.template.IconRenderer';
}


/**
 * @param {pstj.ds.template.IconTemplate.Params} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.UnsanitizedText}
 * @suppress {checkTypes}
 */
pstj.ds.template.IconTemplate = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  /** @type {!Array<!goog.soy.data.UnsanitizedText|string>} */
  var templates = soy.asserts.assertType(goog.isArray(opt_data.templates), 'templates', opt_data.templates, '!Array<!goog.soy.data.UnsanitizedText|string>');
  /** @type {!Array<!goog.soy.data.UnsanitizedText|string>} */
  var names = soy.asserts.assertType(goog.isArray(opt_data.names), 'names', opt_data.names, '!Array<!goog.soy.data.UnsanitizedText|string>');
  var output = '\n{namespace pstj.autogen.template.icons}\n';
  var t24List = templates;
  var t24ListLen = t24List.length;
  for (var t24Index = 0; t24Index < t24ListLen; t24Index++) {
    var t24Data = t24List[t24Index];
    output += '\n\n\n/** Template for icon */\n{template .' + '' + names[/** @type {?} */ (t24Index)] + '}\n' + '' + t24Data + '\n{/template}\n';
  }
  return soydata.markUnsanitizedText(output);
};
/**
 * @typedef {{
 *  templates: !Array<!goog.soy.data.UnsanitizedText|string>,
 *  names: !Array<!goog.soy.data.UnsanitizedText|string>,
 * }}
 */
pstj.ds.template.IconTemplate.Params;
if (goog.DEBUG) {
  pstj.ds.template.IconTemplate.soyTemplateName = 'pstj.ds.template.IconTemplate';
}


/**
 * @param {pstj.ds.template.IconNames.Params} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.ds.template.IconNames = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  /** @type {!Array<!goog.soy.data.UnsanitizedText|string>} */
  var names = soy.asserts.assertType(goog.isArray(opt_data.names), 'names', opt_data.names, '!Array<!goog.soy.data.UnsanitizedText|string>');
  /** @type {!Array<!goog.soy.data.UnsanitizedText|string>} */
  var symbols = soy.asserts.assertType(goog.isArray(opt_data.symbols), 'symbols', opt_data.symbols, '!Array<!goog.soy.data.UnsanitizedText|string>');
  var output = '\n// File auto-generated, please do not edit!\ngoog.provide(\'pstj.autogen.icons.names\');\n\n\n/**\n * Provides the name of known icons.\n *\n * Note that those are automatically extracted from the source svg file(s).\n *\n * @enum {string}\n */\npstj.autogen.icons.names = {\n  NONE: \'none\',\n';
  var name33List = names;
  var name33ListLen = name33List.length;
  for (var name33Index = 0; name33Index < name33ListLen; name33Index++) {
    var name33Data = name33List[name33Index];
    output += '  ' + soy.$$escapeHtml(symbols[/** @type {?} */ (name33Index)]) + ': \'' + soy.$$escapeHtml(name33Data) + '\',\n';
  }
  output += '  NONEXISTING: \'nonexisting\'\n};\n';
  return soydata.VERY_UNSAFE.ordainSanitizedHtml(output);
};
/**
 * @typedef {{
 *  names: !Array<!goog.soy.data.UnsanitizedText|string>,
 *  symbols: !Array<!goog.soy.data.UnsanitizedText|string>,
 * }}
 */
pstj.ds.template.IconNames.Params;
if (goog.DEBUG) {
  pstj.ds.template.IconNames.soyTemplateName = 'pstj.ds.template.IconNames';
}
