// This file was automatically generated by the Soy compiler.
// Please don't edit this file by hand.
// source: templates/pstj.soy

/**
 * @fileoverview Templates in namespace pstj.templates.
 * @public
 */

goog.provide('pstj.templates');

goog.require('goog.soy.data.UnsanitizedText');
goog.require('pstj.material.template');
goog.require('soy');
goog.require('soy.asserts');
goog.require('soydata.VERY_UNSAFE');


/**
 * @param {Object<string, *>=} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.templates.CustomScrollArea = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('custom-scroll-area')) + '"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.templates.CustomScrollArea templates/pstj.soy:10"' : '') + '><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('custom-scroll-internal')) + '"><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('custom-scroll-div')) + '"></div></div><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('custom-scroll-bar')) + ' ' + soy.$$escapeHtmlAttribute(goog.getCssName('goog-slider')) + '"><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('custom-scroll-bar-line')) + '"></div><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('goog-slider-thumb')) + ' ' + soy.$$escapeHtmlAttribute(goog.getCssName('custom-scroll-bar-thumb')) + '"></div></div></div>');
};
if (goog.DEBUG) {
  pstj.templates.CustomScrollArea.soyTemplateName = 'pstj.templates.CustomScrollArea';
}


/**
 * @param {Object<string, *>=} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.templates.page = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-pager-item')) + '"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.templates.page templates/pstj.soy:25"' : '') + '><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-pager-item-vertical-adjustment')) + '"><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-pager-item-text')) + '" data-model="description"></div></div></div>');
};
if (goog.DEBUG) {
  pstj.templates.page.soyTemplateName = 'pstj.templates.page';
}


/**
 * @param {pstj.templates.pager.Params} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.templates.pager = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  /** @type {number} */
  var itemsCount = soy.asserts.assertType(goog.isNumber(opt_data.itemsCount), 'itemsCount', opt_data.itemsCount, 'number');
  var output = '<div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-pager-wrapper')) + '"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.templates.pager templates/pstj.soy:38"' : '') + '><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-pager-items')) + '">';
  var item7607ListLen = Math.max(0, Math.ceil((itemsCount - 0) / 1));
  for (var item7607Index = 0; item7607Index < item7607ListLen; item7607Index++) {
    var item7607Data = 0 + item7607Index * 1;
    output += pstj.templates.page(null, opt_ijData);
  }
  output += '</div><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-pager-page-indicator')) + '">';
  /** @desc The word page in the page N of number of X pages */
  var MSG_UNNAMED = goog.getMsg('Page');
  output += MSG_UNNAMED;
  output += ' <span class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-pager-page')) + '"></span> ';
  /** @desc the word of in page N of X pages */
  var MSG_UNNAMED$$1 = goog.getMsg('of');
  output += MSG_UNNAMED$$1;
  output += ' <span class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-pager-pages')) + '"></span></div></div>';
  return soydata.VERY_UNSAFE.ordainSanitizedHtml(output);
};
/**
 * @typedef {{
 *  itemsCount: number,
 * }}
 */
pstj.templates.pager.Params;
if (goog.DEBUG) {
  pstj.templates.pager.soyTemplateName = 'pstj.templates.pager';
}


/**
 * @param {pstj.templates.listitem.Params} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.templates.listitem = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  /** @type {!goog.soy.data.UnsanitizedText|string} */
  var thumbnail = soy.asserts.assertType(goog.isString(opt_data.thumbnail) || opt_data.thumbnail instanceof goog.soy.data.UnsanitizedText, 'thumbnail', opt_data.thumbnail, '!goog.soy.data.UnsanitizedText|string');
  /** @type {!goog.soy.data.UnsanitizedText|string} */
  var name = soy.asserts.assertType(goog.isString(opt_data.name) || opt_data.name instanceof goog.soy.data.UnsanitizedText, 'name', opt_data.name, '!goog.soy.data.UnsanitizedText|string');
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-list-item')) + '"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.templates.listitem templates/pstj.soy:61"' : '') + '><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-list-item-container')) + '"><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-list-item-image-holder')) + '"><img src="' + soy.$$escapeHtmlAttribute(soy.$$filterNormalizeMediaUri(thumbnail)) + '" class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-list-item-thumbnail')) + '"/></div><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-list-item-name')) + '">' + soy.$$escapeHtml(name) + '</div></div></div>');
};
/**
 * @typedef {{
 *  thumbnail: (!goog.soy.data.UnsanitizedText|string),
 *  name: (!goog.soy.data.UnsanitizedText|string),
 * }}
 */
pstj.templates.listitem.Params;
if (goog.DEBUG) {
  pstj.templates.listitem.soyTemplateName = 'pstj.templates.listitem';
}


/**
 * @param {Object<string, *>=} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.templates.list = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-list')) + '"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.templates.list templates/pstj.soy:75"' : '') + '><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-list-container')) + '"><span class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-list-notice')) + '"></span></div></div>');
};
if (goog.DEBUG) {
  pstj.templates.list.soyTemplateName = 'pstj.templates.list';
}


/**
 * @param {pstj.templates.upload.Params} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.templates.upload = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  /** @type {!goog.soy.data.UnsanitizedText|string} */
  var url = soy.asserts.assertType(goog.isString(opt_data.url) || opt_data.url instanceof goog.soy.data.UnsanitizedText, 'url', opt_data.url, '!goog.soy.data.UnsanitizedText|string');
  /** @type {!goog.soy.data.UnsanitizedText|string} */
  var inputname = soy.asserts.assertType(goog.isString(opt_data.inputname) || opt_data.inputname instanceof goog.soy.data.UnsanitizedText, 'inputname', opt_data.inputname, '!goog.soy.data.UnsanitizedText|string');
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-upload-form')) + '"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.templates.upload templates/pstj.soy:88"' : '') + '><form method="post" enctype="multipart/form-data" action="' + soy.$$escapeHtmlAttribute(soy.$$filterNormalizeUri(url)) + '" name="uploadform"><input id="attachment" name="' + soy.$$escapeHtmlAttribute(inputname) + '" type="file" style="display:none" class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-upload-form-input')) + '"/></form></div>');
};
/**
 * @typedef {{
 *  url: (!goog.soy.data.UnsanitizedText|string),
 *  inputname: (!goog.soy.data.UnsanitizedText|string),
 * }}
 */
pstj.templates.upload.Params;
if (goog.DEBUG) {
  pstj.templates.upload.soyTemplateName = 'pstj.templates.upload';
}


/**
 * @param {Object<string, *>=} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.templates.controlgroup = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-control-group')) + ' ' + soy.$$escapeHtmlAttribute(goog.getCssName('d-table')) + '"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.templates.controlgroup templates/pstj.soy:102"' : '') + '><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-control-group-button')) + ' ' + soy.$$escapeHtmlAttribute(goog.getCssName('d-table-cell')) + '" data-action="namedaction"><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('d-table')) + ' ' + soy.$$escapeHtmlAttribute(goog.getCssName('margin-auto')) + '"><img src="assets/left-arrow.png" class="' + soy.$$escapeHtmlAttribute(goog.getCssName('d-table-cell')) + ' ' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-control-group-button-image')) + '"/></div></div></div>');
};
if (goog.DEBUG) {
  pstj.templates.controlgroup.soyTemplateName = 'pstj.templates.controlgroup';
}


/**
 * @param {pstj.templates.progress.Params} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.templates.progress = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  /** @type {!goog.soy.data.UnsanitizedText|string} */
  var text = soy.asserts.assertType(goog.isString(opt_data.text) || opt_data.text instanceof goog.soy.data.UnsanitizedText, 'text', opt_data.text, '!goog.soy.data.UnsanitizedText|string');
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-widget-progress')) + '"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.templates.progress templates/pstj.soy:116"' : '') + '>' + (!soy.$$equals(text, '') ? '<div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-widget-progress-text')) + '">' + soy.$$escapeHtml(text) + '</div>' : '') + '<div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-widget-progress-container')) + '"><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-widget-progress-bar')) + '"></div></div></div>');
};
/**
 * @typedef {{
 *  text: (!goog.soy.data.UnsanitizedText|string),
 * }}
 */
pstj.templates.progress.Params;
if (goog.DEBUG) {
  pstj.templates.progress.soyTemplateName = 'pstj.templates.progress';
}


/**
 * @param {Object<string, *>=} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.templates.select = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  var output = '<div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-widget-select')) + '"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.templates.select templates/pstj.soy:133"' : '') + '><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-widget-select-view')) + '"><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-widget-select-title')) + '">';
  /** @desc Select item */
  var MSG_UNNAMED = goog.getMsg('Select item');
  output += MSG_UNNAMED;
  output += '</div><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-widget-select-body')) + '">' + pstj.templates.list(null, opt_ijData) + '</div><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-widget-select-footer')) + '"><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('form-button')) + ' ' + soy.$$escapeHtmlAttribute(goog.getCssName('text-button')) + ' ' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-widget-select-text-button')) + ' ' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-action-select')) + '" data-action="select">';
  /** @desc Select */
  var MSG_UNNAMED$$1 = goog.getMsg('Select');
  output += MSG_UNNAMED$$1;
  output += '</div><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('form-button')) + ' ' + soy.$$escapeHtmlAttribute(goog.getCssName('text-button')) + ' ' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-widget-select-text-button')) + ' ' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-action-cancel')) + '" data-action="cancel">';
  /** @desc Cancel */
  var MSG_UNNAMED$$2 = goog.getMsg('Cancel');
  output += MSG_UNNAMED$$2;
  output += '</div></div></div></div>';
  return soydata.VERY_UNSAFE.ordainSanitizedHtml(output);
};
if (goog.DEBUG) {
  pstj.templates.select.soyTemplateName = 'pstj.templates.select';
}


/**
 * @param {Object<string, *>=} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.templates.popover = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-popover-event-blocker')) + '"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.templates.popover templates/pstj.soy:152"' : '') + '><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-popover-frame')) + '"></div></div>');
};
if (goog.DEBUG) {
  pstj.templates.popover.soyTemplateName = 'pstj.templates.popover';
}


/**
 * @param {Object<string, *>=} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.templates.Control = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<div' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.templates.Control templates/pstj.soy:161"' : '') + '></div>');
};
if (goog.DEBUG) {
  pstj.templates.Control.soyTemplateName = 'pstj.templates.Control';
}


/**
 * @param {Object<string, *>=} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.templates.clock = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-widget-clock')) + '"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.templates.clock templates/pstj.soy:170"' : '') + '><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-widget-clock-time')) + '" data-model="time" data-filter="datetime(HH:mm:ss)"></div></div>');
};
if (goog.DEBUG) {
  pstj.templates.clock.soyTemplateName = 'pstj.templates.clock';
}


/**
 * @param {Object<string, *>=} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.templates.TableViewItem = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('tableviewitem')) + '"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.templates.TableViewItem templates/pstj.soy:179"' : '') + '><div data-model="id"></div></div>');
};
if (goog.DEBUG) {
  pstj.templates.TableViewItem.soyTemplateName = 'pstj.templates.TableViewItem';
}


/**
 * @param {pstj.templates.Swipetile.Params} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.templates.Swipetile = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  /** @type {!goog.soy.data.UnsanitizedText|string} */
  var src = soy.asserts.assertType(goog.isString(opt_data.src) || opt_data.src instanceof goog.soy.data.UnsanitizedText, 'src', opt_data.src, '!goog.soy.data.UnsanitizedText|string');
  /** @type {!goog.soy.data.UnsanitizedText|null|string|undefined} */
  var text = soy.asserts.assertType(opt_data.text == null || (goog.isString(opt_data.text) || opt_data.text instanceof goog.soy.data.UnsanitizedText), 'text', opt_data.text, '!goog.soy.data.UnsanitizedText|null|string|undefined');
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<div is class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-swipetile')) + '"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.templates.Swipetile templates/pstj.soy:189"' : '') + '><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-swipetile-image')) + '" style="background-image: url(' + soy.$$escapeHtmlAttribute(soy.$$filterNormalizeMediaUri(src)) + ')">' + (text ? '<div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-swipetile-text-container')) + '"><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-swipetile-text')) + '">' + soy.$$escapeHtml(text) + '</div></div>' : '') + '</div></div>');
};
/**
 * @typedef {{
 *  src: (!goog.soy.data.UnsanitizedText|string),
 *  text: (!goog.soy.data.UnsanitizedText|null|string|undefined),
 * }}
 */
pstj.templates.Swipetile.Params;
if (goog.DEBUG) {
  pstj.templates.Swipetile.soyTemplateName = 'pstj.templates.Swipetile';
}


/**
 * @param {pstj.templates.Swiper.Params} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.templates.Swiper = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  /** @type {!Array<?>} */
  var items = soy.asserts.assertType(goog.isArray(opt_data.items), 'items', opt_data.items, '!Array<?>');
  var output = '<div is class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-swiper')) + ' ' + soy.$$escapeHtmlAttribute(goog.getCssName('core-swipe')) + '" use-pointer' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.templates.Swiper templates/pstj.soy:203"' : '') + '>';
  var item8058List = items;
  var item8058ListLen = item8058List.length;
  for (var item8058Index = 0; item8058Index < item8058ListLen; item8058Index++) {
    var item8058Data = item8058List[item8058Index];
    output += pstj.templates.Swipetile(/** @type {?} */ (item8058Data), opt_ijData);
  }
  output += '</div>';
  return soydata.VERY_UNSAFE.ordainSanitizedHtml(output);
};
/**
 * @typedef {{
 *  items: !Array<?>,
 * }}
 */
pstj.templates.Swiper.Params;
if (goog.DEBUG) {
  pstj.templates.Swiper.soyTemplateName = 'pstj.templates.Swiper';
}


/**
 * @param {Object<string, *>=} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.templates.AppPage = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<div is class="' + soy.$$escapeHtmlAttribute(goog.getCssName('app-page')) + '"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.templates.AppPage templates/pstj.soy:215"' : '') + '></div>');
};
if (goog.DEBUG) {
  pstj.templates.AppPage.soyTemplateName = 'pstj.templates.AppPage';
}


/**
 * @param {Object<string, *>=} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.templates.AppPages = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<div is class="' + soy.$$escapeHtmlAttribute(goog.getCssName('app-pages')) + '"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.templates.AppPages templates/pstj.soy:220"' : '') + '></div>');
};
if (goog.DEBUG) {
  pstj.templates.AppPages.soyTemplateName = 'pstj.templates.AppPages';
}


/**
 * @param {pstj.templates.ErrorMsg.Params} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.templates.ErrorMsg = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  opt_data = opt_data || {};
  /** @type {null|number|undefined} */
  var delay = soy.asserts.assertType(opt_data.delay == null || goog.isNumber(opt_data.delay), 'delay', opt_data.delay, 'null|number|undefined');
  /** @type {boolean|null|undefined} */
  var auto = soy.asserts.assertType(opt_data.auto == null || (goog.isBoolean(opt_data.auto) || opt_data.auto === 1 || opt_data.auto === 0), 'auto', opt_data.auto, 'boolean|null|undefined');
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<div is class="' + soy.$$escapeHtmlAttribute(goog.getCssName('error-msg')) + ' ' + soy.$$escapeHtmlAttribute(goog.getCssName('error-msg-disabled')) + '"' + (soy.$$equals(auto, true) ? ' auto' : '') + (delay ? ' delay="' + soy.$$escapeHtmlAttribute(delay) + '"' : '') + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.templates.ErrorMsg templates/pstj.soy:227"' : '') + '></div>');
};
/**
 * @typedef {{
 *  delay: (null|number|undefined),
 *  auto: (boolean|null|undefined),
 * }}
 */
pstj.templates.ErrorMsg.Params;
if (goog.DEBUG) {
  pstj.templates.ErrorMsg.soyTemplateName = 'pstj.templates.ErrorMsg';
}


/**
 * @param {pstj.templates.ListHeaderCell.Params} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.templates.ListHeaderCell = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  /** @type {!goog.soy.data.UnsanitizedText|string} */
  var label = soy.asserts.assertType(goog.isString(opt_data.label) || opt_data.label instanceof goog.soy.data.UnsanitizedText, 'label', opt_data.label, '!goog.soy.data.UnsanitizedText|string');
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<div is class="' + soy.$$escapeHtmlAttribute(goog.getCssName('list-header-cell')) + '" use-pointer' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.templates.ListHeaderCell templates/pstj.soy:233"' : '') + '><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('flex-1')) + '">' + soy.$$escapeHtml(label) + '</div><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('list-header-icon')) + '">' + pstj.material.template.IconContainer(/** @type {?} */ ({type: 'none'}), opt_ijData) + '</div></div>');
};
/**
 * @typedef {{
 *  label: (!goog.soy.data.UnsanitizedText|string),
 * }}
 */
pstj.templates.ListHeaderCell.Params;
if (goog.DEBUG) {
  pstj.templates.ListHeaderCell.soyTemplateName = 'pstj.templates.ListHeaderCell';
}


/**
 * @param {pstj.templates.ListHeader.Params} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.templates.ListHeader = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  /** @type {!Array<!goog.soy.data.UnsanitizedText|string>} */
  var cells = soy.asserts.assertType(goog.isArray(opt_data.cells), 'cells', opt_data.cells, '!Array<!goog.soy.data.UnsanitizedText|string>');
  /** @type {!Array<number>} */
  var flexes = soy.asserts.assertType(goog.isArray(opt_data.flexes), 'flexes', opt_data.flexes, '!Array<number>');
  var output = '<div is class="' + soy.$$escapeHtmlAttribute(goog.getCssName('list-header')) + ' ' + soy.$$escapeHtmlAttribute(goog.getCssName('core-tap')) + '"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.templates.ListHeader templates/pstj.soy:248"' : '') + '><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('list-header-subhead')) + '">';
  var label8157List = cells;
  var label8157ListLen = label8157List.length;
  for (var label8157Index = 0; label8157Index < label8157ListLen; label8157Index++) {
    var label8157Data = label8157List[label8157Index];
    output += '<div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('list-header-item'));
    var local_index__soy8165 = label8157Index;
    if (flexes[/** @type {?} */ (local_index__soy8165)]) {
      var flex__soy8168 = flexes[/** @type {?} */ (local_index__soy8165)];
      switch (flex__soy8168) {
        case 1:
          output += soy.$$escapeHtmlAttribute(goog.getCssName('flex-1'));
          break;
        case 2:
          output += soy.$$escapeHtmlAttribute(goog.getCssName('flex-2'));
          break;
        case 3:
          output += soy.$$escapeHtmlAttribute(goog.getCssName('flex-3'));
          break;
        case 4:
          output += soy.$$escapeHtmlAttribute(goog.getCssName('flex-4'));
          break;
        case 5:
          output += soy.$$escapeHtmlAttribute(goog.getCssName('flex-5'));
          break;
      }
    }
    output += '">' + pstj.templates.ListHeaderCell(/** @type {?} */ ({label: label8157Data}), opt_ijData) + '</div>';
  }
  output += '</div></div>';
  return soydata.VERY_UNSAFE.ordainSanitizedHtml(output);
};
/**
 * @typedef {{
 *  cells: !Array<!goog.soy.data.UnsanitizedText|string>,
 *  flexes: !Array<number>,
 * }}
 */
pstj.templates.ListHeader.Params;
if (goog.DEBUG) {
  pstj.templates.ListHeader.soyTemplateName = 'pstj.templates.ListHeader';
}
