// This file was automatically generated by the Soy compiler.
// Please don't edit this file by hand.
// source: templates/select.soy

/**
 * @fileoverview Templates in namespace pstj.select.
 * @public
 */

goog.provide('pstj.select');

goog.require('goog.soy.data.UnsanitizedText');
goog.require('soy');
goog.require('soy.asserts');
goog.require('soydata.VERY_UNSAFE');


/**
 * @param {Object<string, *>=} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.select.Select = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  var output = '<div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-select')) + '"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Select templates/select.soy:7"' : '') + '><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-select-view')) + '"><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-select-title')) + '">';
  /** @desc Select item */
  var MSG_UNNAMED = goog.getMsg('Select item');
  output += MSG_UNNAMED;
  output += '</div><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-select-body')) + '"></div><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-select-footer')) + '"><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('form-button')) + ' ' + soy.$$escapeHtmlAttribute(goog.getCssName('text-button')) + ' ' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-select-text-button')) + ' ' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-action-select')) + '">';
  /** @desc Select */
  var MSG_UNNAMED$$1 = goog.getMsg('Select');
  output += MSG_UNNAMED$$1;
  output += '</div><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('form-button')) + ' ' + soy.$$escapeHtmlAttribute(goog.getCssName('text-button')) + ' ' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-select-text-button')) + ' ' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-action-cancel')) + '">';
  /** @desc Cancel */
  var MSG_UNNAMED$$2 = goog.getMsg('Cancel');
  output += MSG_UNNAMED$$2;
  output += '</div></div></div></div>';
  return soydata.VERY_UNSAFE.ordainSanitizedHtml(output);
};
if (goog.DEBUG) {
  pstj.select.Select.soyTemplateName = 'pstj.select.Select';
}


/**
 * @param {pstj.select.SelectionItem.Params} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.select.SelectionItem = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  /** @type {!goog.soy.data.UnsanitizedText|string} */
  var thumbnail = soy.asserts.assertType(goog.isString(opt_data.thumbnail) || opt_data.thumbnail instanceof goog.soy.data.UnsanitizedText, 'thumbnail', opt_data.thumbnail, '!goog.soy.data.UnsanitizedText|string');
  /** @type {!goog.soy.data.UnsanitizedText|string} */
  var name = soy.asserts.assertType(goog.isString(opt_data.name) || opt_data.name instanceof goog.soy.data.UnsanitizedText, 'name', opt_data.name, '!goog.soy.data.UnsanitizedText|string');
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-select-item')) + '"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.SelectionItem templates/select.soy:25"' : '') + '><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-select-item-image-holder')) + '"><img src="' + soy.$$escapeHtmlAttribute(soy.$$filterNormalizeMediaUri(thumbnail)) + '" class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-select-item-thumbnail')) + '"/></div><div class="' + soy.$$escapeHtmlAttribute(goog.getCssName('pstj-select-item-name')) + '">' + soy.$$escapeHtml(name) + '</div></div>');
};
/**
 * @typedef {{
 *  thumbnail: (!goog.soy.data.UnsanitizedText|string),
 *  name: (!goog.soy.data.UnsanitizedText|string),
 * }}
 */
pstj.select.SelectionItem.Params;
if (goog.DEBUG) {
  pstj.select.SelectionItem.soyTemplateName = 'pstj.select.SelectionItem';
}


/**
 * @param {Object<string, *>=} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.select.USAStates = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  var output = '<option value="Non-US/Other"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:36"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED = goog.getMsg('Non-US/Other');
  output += MSG_UNNAMED;
  output += '</option><option value="Alabama"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:37"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$1 = goog.getMsg('Alabama');
  output += MSG_UNNAMED$$1;
  output += '</option><option value="Alaska"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:38"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$2 = goog.getMsg('Alaska');
  output += MSG_UNNAMED$$2;
  output += '</option><option value="Arizona"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:39"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$3 = goog.getMsg('Arizona');
  output += MSG_UNNAMED$$3;
  output += '</option><option value="Arkansas"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:40"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$4 = goog.getMsg('Arkansas');
  output += MSG_UNNAMED$$4;
  output += '</option><option value="California"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:41"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$5 = goog.getMsg('California');
  output += MSG_UNNAMED$$5;
  output += '</option><option value="Colorado"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:42"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$6 = goog.getMsg('Colorado');
  output += MSG_UNNAMED$$6;
  output += '</option><option value="Connecticut"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:43"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$7 = goog.getMsg('Connecticut');
  output += MSG_UNNAMED$$7;
  output += '</option><option value="District of Columbia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:44"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$8 = goog.getMsg('District of Columbia');
  output += MSG_UNNAMED$$8;
  output += '</option><option value="Delaware"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:45"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$9 = goog.getMsg('Delaware');
  output += MSG_UNNAMED$$9;
  output += '</option><option value="Florida"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:46"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$10 = goog.getMsg('Florida');
  output += MSG_UNNAMED$$10;
  output += '</option><option value="Georgia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:47"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$11 = goog.getMsg('Georgia');
  output += MSG_UNNAMED$$11;
  output += '</option><option value="Hawaii"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:48"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$12 = goog.getMsg('Hawaii');
  output += MSG_UNNAMED$$12;
  output += '</option><option value="Idaho"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:49"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$13 = goog.getMsg('Idaho');
  output += MSG_UNNAMED$$13;
  output += '</option><option value="Illinois"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:50"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$14 = goog.getMsg('Illinois');
  output += MSG_UNNAMED$$14;
  output += '</option><option value="Indiana"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:51"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$15 = goog.getMsg('Indiana');
  output += MSG_UNNAMED$$15;
  output += '</option><option value="Iowa"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:52"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$16 = goog.getMsg('Iowa');
  output += MSG_UNNAMED$$16;
  output += '</option><option value="Kansas"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:53"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$17 = goog.getMsg('Kansas');
  output += MSG_UNNAMED$$17;
  output += '</option><option value="Kentucky"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:54"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$18 = goog.getMsg('Kentucky');
  output += MSG_UNNAMED$$18;
  output += '</option><option value="Louisiana"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:55"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$19 = goog.getMsg('Louisiana');
  output += MSG_UNNAMED$$19;
  output += '</option><option value="Maine"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:56"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$20 = goog.getMsg('Maine');
  output += MSG_UNNAMED$$20;
  output += '</option><option value="Maryland"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:57"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$21 = goog.getMsg('Maryland');
  output += MSG_UNNAMED$$21;
  output += '</option><option value="Massachusetts"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:58"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$22 = goog.getMsg('Massachusetts');
  output += MSG_UNNAMED$$22;
  output += '</option><option value="Michigan"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:59"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$23 = goog.getMsg('Michigan');
  output += MSG_UNNAMED$$23;
  output += '</option><option value="Minnesota"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:60"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$24 = goog.getMsg('Minnesota');
  output += MSG_UNNAMED$$24;
  output += '</option><option value="Mississippi"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:61"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$25 = goog.getMsg('Mississippi');
  output += MSG_UNNAMED$$25;
  output += '</option><option value="Missouri"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:62"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$26 = goog.getMsg('Missouri');
  output += MSG_UNNAMED$$26;
  output += '</option><option value="Montana"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:63"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$27 = goog.getMsg('Montana');
  output += MSG_UNNAMED$$27;
  output += '</option><option value="Nebraska"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:64"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$28 = goog.getMsg('Nebraska');
  output += MSG_UNNAMED$$28;
  output += '</option><option value="Nevada"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:65"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$29 = goog.getMsg('Nevada');
  output += MSG_UNNAMED$$29;
  output += '</option><option value="New Hampshire"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:66"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$30 = goog.getMsg('New Hampshire');
  output += MSG_UNNAMED$$30;
  output += '</option><option value="New Jersey"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:67"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$31 = goog.getMsg('New Jersey');
  output += MSG_UNNAMED$$31;
  output += '</option><option value="New Mexico"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:68"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$32 = goog.getMsg('New Mexico');
  output += MSG_UNNAMED$$32;
  output += '</option><option value="New York"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:69"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$33 = goog.getMsg('New York');
  output += MSG_UNNAMED$$33;
  output += '</option><option value="North Carolina"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:70"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$34 = goog.getMsg('North Carolina');
  output += MSG_UNNAMED$$34;
  output += '</option><option value="North Dakota"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:71"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$35 = goog.getMsg('North Dakota');
  output += MSG_UNNAMED$$35;
  output += '</option><option value="Ohio"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:72"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$36 = goog.getMsg('Ohio');
  output += MSG_UNNAMED$$36;
  output += '</option><option value="Oklahoma"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:73"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$37 = goog.getMsg('Oklahoma');
  output += MSG_UNNAMED$$37;
  output += '</option><option value="Oregon"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:74"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$38 = goog.getMsg('Oregon');
  output += MSG_UNNAMED$$38;
  output += '</option><option value="Pennsylvania"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:75"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$39 = goog.getMsg('Pennsylvania');
  output += MSG_UNNAMED$$39;
  output += '</option><option value="Puerto Rico"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:76"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$40 = goog.getMsg('Puerto Rico');
  output += MSG_UNNAMED$$40;
  output += '</option><option value="Rhode Island"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:77"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$41 = goog.getMsg('Rhode Island');
  output += MSG_UNNAMED$$41;
  output += '</option><option value="South Carolina"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:78"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$42 = goog.getMsg('South Carolina');
  output += MSG_UNNAMED$$42;
  output += '</option><option value="South Dakota"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:79"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$43 = goog.getMsg('South Dakota');
  output += MSG_UNNAMED$$43;
  output += '</option><option value="Tennessee"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:80"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$44 = goog.getMsg('Tennessee');
  output += MSG_UNNAMED$$44;
  output += '</option><option value="Texas"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:81"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$45 = goog.getMsg('Texas');
  output += MSG_UNNAMED$$45;
  output += '</option><option value="Utah"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:82"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$46 = goog.getMsg('Utah');
  output += MSG_UNNAMED$$46;
  output += '</option><option value="Vermont"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:83"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$47 = goog.getMsg('Vermont');
  output += MSG_UNNAMED$$47;
  output += '</option><option value="Virginia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:84"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$48 = goog.getMsg('Virginia');
  output += MSG_UNNAMED$$48;
  output += '</option><option value="Washington"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:85"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$49 = goog.getMsg('Washington');
  output += MSG_UNNAMED$$49;
  output += '</option><option value="West Virginia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:86"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$50 = goog.getMsg('West Virginia');
  output += MSG_UNNAMED$$50;
  output += '</option><option value="Wisconsin"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:87"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$51 = goog.getMsg('Wisconsin');
  output += MSG_UNNAMED$$51;
  output += '</option><option value="Wyoming"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.USAStates templates/select.soy:88"' : '') + '>';
  /** @desc state */
  var MSG_UNNAMED$$52 = goog.getMsg('Wyoming');
  output += MSG_UNNAMED$$52;
  output += '</option>';
  return soydata.VERY_UNSAFE.ordainSanitizedHtml(output);
};
if (goog.DEBUG) {
  pstj.select.USAStates.soyTemplateName = 'pstj.select.USAStates';
}


/**
 * @param {Object<string, *>=} opt_data
 * @param {soy.IjData|Object<string, *>=} opt_ijData
 * @param {soy.IjData|Object<string, *>=} opt_ijData_deprecated
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
pstj.select.Countries = function(opt_data, opt_ijData, opt_ijData_deprecated) {
  opt_ijData = /** @type {!soy.IjData} */ (opt_ijData_deprecated || opt_ijData);
  var output = '<option value="United States"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:94"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED = goog.getMsg('United States');
  output += MSG_UNNAMED;
  output += '</option><option value="Afghanistan"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:95"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$1 = goog.getMsg('Afghanistan');
  output += MSG_UNNAMED$$1;
  output += '</option><option value="Albania"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:96"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$2 = goog.getMsg('Albania');
  output += MSG_UNNAMED$$2;
  output += '</option><option value="Algeria"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:97"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$3 = goog.getMsg('Algeria');
  output += MSG_UNNAMED$$3;
  output += '</option><option value="American Samoa"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:98"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$4 = goog.getMsg('American Samoa');
  output += MSG_UNNAMED$$4;
  output += '</option><option value="Andorra"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:99"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$5 = goog.getMsg('Andorra');
  output += MSG_UNNAMED$$5;
  output += '</option><option value="Angola"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:100"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$6 = goog.getMsg('Angola');
  output += MSG_UNNAMED$$6;
  output += '</option><option value="Anguilla"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:101"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$7 = goog.getMsg('Anguilla');
  output += MSG_UNNAMED$$7;
  output += '</option><option value="Antarctica"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:102"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$8 = goog.getMsg('Antarctica');
  output += MSG_UNNAMED$$8;
  output += '</option><option value="Antigua and Barbuda"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:103"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$9 = goog.getMsg('Antigua and Barbuda');
  output += MSG_UNNAMED$$9;
  output += '</option><option value="Argentina"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:104"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$10 = goog.getMsg('Argentina');
  output += MSG_UNNAMED$$10;
  output += '</option><option value="Armenia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:105"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$11 = goog.getMsg('Armenia');
  output += MSG_UNNAMED$$11;
  output += '</option><option value="Aruba"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:106"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$12 = goog.getMsg('Aruba');
  output += MSG_UNNAMED$$12;
  output += '</option><option value="Australia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:107"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$13 = goog.getMsg('Australia');
  output += MSG_UNNAMED$$13;
  output += '</option><option value="Austria"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:108"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$14 = goog.getMsg('Austria');
  output += MSG_UNNAMED$$14;
  output += '</option><option value="Azerbaijan"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:109"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$15 = goog.getMsg('Azerbaijan');
  output += MSG_UNNAMED$$15;
  output += '</option><option value="Bahamas"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:110"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$16 = goog.getMsg('Bahamas');
  output += MSG_UNNAMED$$16;
  output += '</option><option value="Bahrain"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:111"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$17 = goog.getMsg('Bahrain');
  output += MSG_UNNAMED$$17;
  output += '</option><option value="Bangladesh"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:112"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$18 = goog.getMsg('Bangladesh');
  output += MSG_UNNAMED$$18;
  output += '</option><option value="Barbados"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:113"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$19 = goog.getMsg('Barbados');
  output += MSG_UNNAMED$$19;
  output += '</option><option value="Belarus"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:114"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$20 = goog.getMsg('Belarus');
  output += MSG_UNNAMED$$20;
  output += '</option><option value="Belgium"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:115"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$21 = goog.getMsg('Belgium');
  output += MSG_UNNAMED$$21;
  output += '</option><option value="Belize"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:116"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$22 = goog.getMsg('Belize');
  output += MSG_UNNAMED$$22;
  output += '</option><option value="Benin"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:117"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$23 = goog.getMsg('Benin');
  output += MSG_UNNAMED$$23;
  output += '</option><option value="Bermuda"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:118"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$24 = goog.getMsg('Bermuda');
  output += MSG_UNNAMED$$24;
  output += '</option><option value="Bhutan"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:119"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$25 = goog.getMsg('Bhutan');
  output += MSG_UNNAMED$$25;
  output += '</option><option value="Bolivia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:120"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$26 = goog.getMsg('Bolivia');
  output += MSG_UNNAMED$$26;
  output += '</option><option value="Bosnia and Herzegovina"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:121"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$27 = goog.getMsg('Bosnia and Herzegovina');
  output += MSG_UNNAMED$$27;
  output += '</option><option value="Botswana"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:122"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$28 = goog.getMsg('Botswana');
  output += MSG_UNNAMED$$28;
  output += '</option><option value="Bouvet Island"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:123"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$29 = goog.getMsg('Bouvet Island');
  output += MSG_UNNAMED$$29;
  output += '</option><option value="Brazil"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:124"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$30 = goog.getMsg('Brazil');
  output += MSG_UNNAMED$$30;
  output += '</option><option value="Brunei Darussalam"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:125"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$31 = goog.getMsg('Brunei Darussalam');
  output += MSG_UNNAMED$$31;
  output += '</option><option value="Bulgaria"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:126"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$32 = goog.getMsg('Bulgaria');
  output += MSG_UNNAMED$$32;
  output += '</option><option value="Burkina Faso"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:127"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$33 = goog.getMsg('Burkina Faso');
  output += MSG_UNNAMED$$33;
  output += '</option><option value="Burundi"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:128"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$34 = goog.getMsg('Burundi');
  output += MSG_UNNAMED$$34;
  output += '</option><option value="Cambodia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:129"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$35 = goog.getMsg('Cambodia');
  output += MSG_UNNAMED$$35;
  output += '</option><option value="Cameroon"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:130"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$36 = goog.getMsg('Cameroon');
  output += MSG_UNNAMED$$36;
  output += '</option><option value="Canada"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:131"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$37 = goog.getMsg('Canada');
  output += MSG_UNNAMED$$37;
  output += '</option><option value="Cape Verde"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:132"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$38 = goog.getMsg('Cape Verde');
  output += MSG_UNNAMED$$38;
  output += '</option><option value="Cayman Islands"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:133"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$39 = goog.getMsg('Cayman Islands');
  output += MSG_UNNAMED$$39;
  output += '</option><option value="Central African Republic"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:134"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$40 = goog.getMsg('Central African Republic');
  output += MSG_UNNAMED$$40;
  output += '</option><option value="Chad"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:135"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$41 = goog.getMsg('Chad');
  output += MSG_UNNAMED$$41;
  output += '</option><option value="Chile"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:136"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$42 = goog.getMsg('Chile');
  output += MSG_UNNAMED$$42;
  output += '</option><option value="China"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:137"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$43 = goog.getMsg('China');
  output += MSG_UNNAMED$$43;
  output += '</option><option value="Christmas Island"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:138"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$44 = goog.getMsg('Christmas Island');
  output += MSG_UNNAMED$$44;
  output += '</option><option value="Cocos (Keeling) Islands"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:139"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$45 = goog.getMsg('Cocos (Keeling) Islands');
  output += MSG_UNNAMED$$45;
  output += '</option><option value="Colombia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:140"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$46 = goog.getMsg('Colombia');
  output += MSG_UNNAMED$$46;
  output += '</option><option value="Comoros"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:141"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$47 = goog.getMsg('Comoros');
  output += MSG_UNNAMED$$47;
  output += '</option><option value="Congo"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:142"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$48 = goog.getMsg('Congo');
  output += MSG_UNNAMED$$48;
  output += '</option><option value="Cook Islands"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:143"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$49 = goog.getMsg('Cook Islands');
  output += MSG_UNNAMED$$49;
  output += '</option><option value="Costa Rica"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:144"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$50 = goog.getMsg('Costa Rica');
  output += MSG_UNNAMED$$50;
  output += '</option><option value="Cote D\'Ivoire"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:145"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$51 = goog.getMsg('Cote D\'Ivoire');
  output += MSG_UNNAMED$$51;
  output += '</option><option value="Croatia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:146"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$52 = goog.getMsg('Croatia');
  output += MSG_UNNAMED$$52;
  output += '</option><option value="Cuba"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:147"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$53 = goog.getMsg('Cuba');
  output += MSG_UNNAMED$$53;
  output += '</option><option value="Cyprus"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:148"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$54 = goog.getMsg('Cyprus');
  output += MSG_UNNAMED$$54;
  output += '</option><option value="Czech Republic"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:149"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$55 = goog.getMsg('Czech Republic');
  output += MSG_UNNAMED$$55;
  output += '</option><option value="Denmark"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:150"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$56 = goog.getMsg('Denmark');
  output += MSG_UNNAMED$$56;
  output += '</option><option value="Djibouti"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:151"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$57 = goog.getMsg('Djibouti');
  output += MSG_UNNAMED$$57;
  output += '</option><option value="Dominica"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:152"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$58 = goog.getMsg('Dominica');
  output += MSG_UNNAMED$$58;
  output += '</option><option value="Dominican Republic"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:153"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$59 = goog.getMsg('Dominican Republic');
  output += MSG_UNNAMED$$59;
  output += '</option><option value="Timor-Leste"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:154"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$60 = goog.getMsg('Timor-Leste');
  output += MSG_UNNAMED$$60;
  output += '</option><option value="Ecuador"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:155"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$61 = goog.getMsg('Ecuador');
  output += MSG_UNNAMED$$61;
  output += '</option><option value="Egypt"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:156"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$62 = goog.getMsg('Egypt');
  output += MSG_UNNAMED$$62;
  output += '</option><option value="El Salvador"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:157"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$63 = goog.getMsg('El Salvador');
  output += MSG_UNNAMED$$63;
  output += '</option><option value="Equatorial Guinea"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:158"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$64 = goog.getMsg('Equatorial Guinea');
  output += MSG_UNNAMED$$64;
  output += '</option><option value="Eritrea"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:159"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$65 = goog.getMsg('Eritrea');
  output += MSG_UNNAMED$$65;
  output += '</option><option value="Estonia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:160"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$66 = goog.getMsg('Estonia');
  output += MSG_UNNAMED$$66;
  output += '</option><option value="Ethiopia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:161"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$67 = goog.getMsg('Ethiopia');
  output += MSG_UNNAMED$$67;
  output += '</option><option value="Falkland Islands (Malvinas)"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:162"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$68 = goog.getMsg('Falkland Islands (Malvinas)');
  output += MSG_UNNAMED$$68;
  output += '</option><option value="Faroe Islands"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:163"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$69 = goog.getMsg('Faroe Islands');
  output += MSG_UNNAMED$$69;
  output += '</option><option value="Fiji"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:164"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$70 = goog.getMsg('Fiji');
  output += MSG_UNNAMED$$70;
  output += '</option><option value="Finland"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:165"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$71 = goog.getMsg('Finland');
  output += MSG_UNNAMED$$71;
  output += '</option><option value="France"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:166"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$72 = goog.getMsg('France');
  output += MSG_UNNAMED$$72;
  output += '</option><option value="France, Metropolitan"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:167"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$73 = goog.getMsg('France, Metropolitan');
  output += MSG_UNNAMED$$73;
  output += '</option><option value="French Guiana"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:168"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$74 = goog.getMsg('French Guiana');
  output += MSG_UNNAMED$$74;
  output += '</option><option value="French Polynesia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:169"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$75 = goog.getMsg('French Polynesia');
  output += MSG_UNNAMED$$75;
  output += '</option><option value="Gabon"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:170"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$76 = goog.getMsg('Gabon');
  output += MSG_UNNAMED$$76;
  output += '</option><option value="Gambia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:171"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$77 = goog.getMsg('Gambia');
  output += MSG_UNNAMED$$77;
  output += '</option><option value="Georgia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:172"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$78 = goog.getMsg('Georgia');
  output += MSG_UNNAMED$$78;
  output += '</option><option value="Germany"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:173"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$79 = goog.getMsg('Germany');
  output += MSG_UNNAMED$$79;
  output += '</option><option value="Ghana"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:174"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$80 = goog.getMsg('Ghana');
  output += MSG_UNNAMED$$80;
  output += '</option><option value="Gibraltar"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:175"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$81 = goog.getMsg('Gibraltar');
  output += MSG_UNNAMED$$81;
  output += '</option><option value="Greece"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:176"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$82 = goog.getMsg('Greece');
  output += MSG_UNNAMED$$82;
  output += '</option><option value="Greenland"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:177"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$83 = goog.getMsg('Greenland');
  output += MSG_UNNAMED$$83;
  output += '</option><option value="Grenada"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:178"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$84 = goog.getMsg('Grenada');
  output += MSG_UNNAMED$$84;
  output += '</option><option value="Guadeloupe"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:179"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$85 = goog.getMsg('Guadeloupe');
  output += MSG_UNNAMED$$85;
  output += '</option><option value="Guam"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:180"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$86 = goog.getMsg('Guam');
  output += MSG_UNNAMED$$86;
  output += '</option><option value="Guatemala"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:181"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$87 = goog.getMsg('Guatemala');
  output += MSG_UNNAMED$$87;
  output += '</option><option value="Guinea"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:182"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$88 = goog.getMsg('Guinea');
  output += MSG_UNNAMED$$88;
  output += '</option><option value="Guinea-Bissau"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:183"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$89 = goog.getMsg('Guinea-Bissau');
  output += MSG_UNNAMED$$89;
  output += '</option><option value="Guyana"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:184"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$90 = goog.getMsg('Guyana');
  output += MSG_UNNAMED$$90;
  output += '</option><option value="Haiti"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:185"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$91 = goog.getMsg('Haiti');
  output += MSG_UNNAMED$$91;
  output += '</option><option value="Honduras"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:186"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$92 = goog.getMsg('Honduras');
  output += MSG_UNNAMED$$92;
  output += '</option><option value="Hong Kong"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:187"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$93 = goog.getMsg('Hong Kong');
  output += MSG_UNNAMED$$93;
  output += '</option><option value="Hungary"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:188"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$94 = goog.getMsg('Hungary');
  output += MSG_UNNAMED$$94;
  output += '</option><option value="Iceland"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:189"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$95 = goog.getMsg('Iceland');
  output += MSG_UNNAMED$$95;
  output += '</option><option value="India"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:190"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$96 = goog.getMsg('India');
  output += MSG_UNNAMED$$96;
  output += '</option><option value="Indonesia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:191"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$97 = goog.getMsg('Indonesia');
  output += MSG_UNNAMED$$97;
  output += '</option><option value="Iran"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:192"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$98 = goog.getMsg('Iran');
  output += MSG_UNNAMED$$98;
  output += '</option><option value="Iraq"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:193"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$99 = goog.getMsg('Iraq');
  output += MSG_UNNAMED$$99;
  output += '</option><option value="Ireland"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:194"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$100 = goog.getMsg('Ireland');
  output += MSG_UNNAMED$$100;
  output += '</option><option value="Israel"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:195"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$101 = goog.getMsg('Israel');
  output += MSG_UNNAMED$$101;
  output += '</option><option value="Italy"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:196"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$102 = goog.getMsg('Italy');
  output += MSG_UNNAMED$$102;
  output += '</option><option value="Jamaica"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:197"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$103 = goog.getMsg('Jamaica');
  output += MSG_UNNAMED$$103;
  output += '</option><option value="Japan"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:198"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$104 = goog.getMsg('Japan');
  output += MSG_UNNAMED$$104;
  output += '</option><option value="Jordan"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:199"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$105 = goog.getMsg('Jordan');
  output += MSG_UNNAMED$$105;
  output += '</option><option value="Kazakhstan"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:200"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$106 = goog.getMsg('Kazakhstan');
  output += MSG_UNNAMED$$106;
  output += '</option><option value="Kenya"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:201"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$107 = goog.getMsg('Kenya');
  output += MSG_UNNAMED$$107;
  output += '</option><option value="Kiribati"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:202"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$108 = goog.getMsg('Kiribati');
  output += MSG_UNNAMED$$108;
  output += '</option><option value="D.P.R. Korea"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:203"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$109 = goog.getMsg('D.P.R. Korea');
  output += MSG_UNNAMED$$109;
  output += '</option><option value="Korea, Republic of"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:204"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$110 = goog.getMsg('Korea, Republic of');
  output += MSG_UNNAMED$$110;
  output += '</option><option value="Kuwait"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:205"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$111 = goog.getMsg('Kuwait');
  output += MSG_UNNAMED$$111;
  output += '</option><option value="Kyrgyzstan"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:206"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$112 = goog.getMsg('Kyrgyzstan');
  output += MSG_UNNAMED$$112;
  output += '</option><option value="Lao People\'s Republic"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:207"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$113 = goog.getMsg('Lao People\'s Republic');
  output += MSG_UNNAMED$$113;
  output += '</option><option value="Latvia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:208"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$114 = goog.getMsg('Latvia');
  output += MSG_UNNAMED$$114;
  output += '</option><option value="Lebanon"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:209"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$115 = goog.getMsg('Lebanon');
  output += MSG_UNNAMED$$115;
  output += '</option><option value="Lesotho"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:210"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$116 = goog.getMsg('Lesotho');
  output += MSG_UNNAMED$$116;
  output += '</option><option value="Liberia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:211"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$117 = goog.getMsg('Liberia');
  output += MSG_UNNAMED$$117;
  output += '</option><option value="Libyan Arab Jamahiriya"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:212"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$118 = goog.getMsg('Libyan Arab Jamahiriya');
  output += MSG_UNNAMED$$118;
  output += '</option><option value="Liechtenstein"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:213"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$119 = goog.getMsg('Liechtenstein');
  output += MSG_UNNAMED$$119;
  output += '</option><option value="Lithuania"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:214"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$120 = goog.getMsg('Lithuania');
  output += MSG_UNNAMED$$120;
  output += '</option><option value="Luxembourg"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:215"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$121 = goog.getMsg('Luxembourg');
  output += MSG_UNNAMED$$121;
  output += '</option><option value="Macao"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:216"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$122 = goog.getMsg('Macao');
  output += MSG_UNNAMED$$122;
  output += '</option><option value="Macedonia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:217"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$123 = goog.getMsg('Macedonia');
  output += MSG_UNNAMED$$123;
  output += '</option><option value="Madagascar"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:218"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$124 = goog.getMsg('Madagascar');
  output += MSG_UNNAMED$$124;
  output += '</option><option value="Malawi"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:219"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$125 = goog.getMsg('Malawi');
  output += MSG_UNNAMED$$125;
  output += '</option><option value="Malaysia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:220"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$126 = goog.getMsg('Malaysia');
  output += MSG_UNNAMED$$126;
  output += '</option><option value="Maldives"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:221"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$127 = goog.getMsg('Maldives');
  output += MSG_UNNAMED$$127;
  output += '</option><option value="Mali"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:222"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$128 = goog.getMsg('Mali');
  output += MSG_UNNAMED$$128;
  output += '</option><option value="Malta"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:223"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$129 = goog.getMsg('Malta');
  output += MSG_UNNAMED$$129;
  output += '</option><option value="Marshall Islands"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:224"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$130 = goog.getMsg('Marshall Islands');
  output += MSG_UNNAMED$$130;
  output += '</option><option value="Martinique"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:225"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$131 = goog.getMsg('Martinique');
  output += MSG_UNNAMED$$131;
  output += '</option><option value="Mauritania"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:226"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$132 = goog.getMsg('Mauritania');
  output += MSG_UNNAMED$$132;
  output += '</option><option value="Mauritius"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:227"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$133 = goog.getMsg('Mauritius');
  output += MSG_UNNAMED$$133;
  output += '</option><option value="Mayotte"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:228"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$134 = goog.getMsg('Mayotte');
  output += MSG_UNNAMED$$134;
  output += '</option><option value="Mexico"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:229"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$135 = goog.getMsg('Mexico');
  output += MSG_UNNAMED$$135;
  output += '</option><option value="Micronesia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:230"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$136 = goog.getMsg('Micronesia');
  output += MSG_UNNAMED$$136;
  output += '</option><option value="Moldova, Republic of"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:231"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$137 = goog.getMsg('Moldova, Republic of');
  output += MSG_UNNAMED$$137;
  output += '</option><option value="Monaco"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:232"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$138 = goog.getMsg('Monaco');
  output += MSG_UNNAMED$$138;
  output += '</option><option value="Mongolia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:233"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$139 = goog.getMsg('Mongolia');
  output += MSG_UNNAMED$$139;
  output += '</option><option value="Montserrat"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:234"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$140 = goog.getMsg('Montserrat');
  output += MSG_UNNAMED$$140;
  output += '</option><option value="Morocco"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:235"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$141 = goog.getMsg('Morocco');
  output += MSG_UNNAMED$$141;
  output += '</option><option value="Mozambique"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:236"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$142 = goog.getMsg('Mozambique');
  output += MSG_UNNAMED$$142;
  output += '</option><option value="Myanmar"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:237"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$143 = goog.getMsg('Myanmar');
  output += MSG_UNNAMED$$143;
  output += '</option><option value="Namibia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:238"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$144 = goog.getMsg('Namibia');
  output += MSG_UNNAMED$$144;
  output += '</option><option value="Nauru"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:239"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$145 = goog.getMsg('Nauru');
  output += MSG_UNNAMED$$145;
  output += '</option><option value="Nepal"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:240"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$146 = goog.getMsg('Nepal');
  output += MSG_UNNAMED$$146;
  output += '</option><option value="Netherlands"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:241"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$147 = goog.getMsg('Netherlands');
  output += MSG_UNNAMED$$147;
  output += '</option><option value="Netherlands Antilles"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:242"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$148 = goog.getMsg('Netherlands Antilles');
  output += MSG_UNNAMED$$148;
  output += '</option><option value="New Caledonia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:243"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$149 = goog.getMsg('New Caledonia');
  output += MSG_UNNAMED$$149;
  output += '</option><option value="New Zealand"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:244"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$150 = goog.getMsg('New Zealand');
  output += MSG_UNNAMED$$150;
  output += '</option><option value="Nicaragua"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:245"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$151 = goog.getMsg('Nicaragua');
  output += MSG_UNNAMED$$151;
  output += '</option><option value="Niger"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:246"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$152 = goog.getMsg('Niger');
  output += MSG_UNNAMED$$152;
  output += '</option><option value="Nigeria"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:247"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$153 = goog.getMsg('Nigeria');
  output += MSG_UNNAMED$$153;
  output += '</option><option value="Niue"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:248"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$154 = goog.getMsg('Niue');
  output += MSG_UNNAMED$$154;
  output += '</option><option value="Norfolk Island"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:249"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$155 = goog.getMsg('Norfolk Island');
  output += MSG_UNNAMED$$155;
  output += '</option><option value="Northern Mariana Islands"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:250"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$156 = goog.getMsg('Northern Mariana Islands');
  output += MSG_UNNAMED$$156;
  output += '</option><option value="Norway"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:251"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$157 = goog.getMsg('Norway');
  output += MSG_UNNAMED$$157;
  output += '</option><option value="Oman"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:252"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$158 = goog.getMsg('Oman');
  output += MSG_UNNAMED$$158;
  output += '</option><option value="Pakistan"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:253"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$159 = goog.getMsg('Pakistan');
  output += MSG_UNNAMED$$159;
  output += '</option><option value="Palau"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:254"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$160 = goog.getMsg('Palau');
  output += MSG_UNNAMED$$160;
  output += '</option><option value="Panama"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:255"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$161 = goog.getMsg('Panama');
  output += MSG_UNNAMED$$161;
  output += '</option><option value="Papua New Guinea"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:256"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$162 = goog.getMsg('Papua New Guinea');
  output += MSG_UNNAMED$$162;
  output += '</option><option value="Paraguay"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:257"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$163 = goog.getMsg('Paraguay');
  output += MSG_UNNAMED$$163;
  output += '</option><option value="Peru"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:258"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$164 = goog.getMsg('Peru');
  output += MSG_UNNAMED$$164;
  output += '</option><option value="Philippines"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:259"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$165 = goog.getMsg('Philippines');
  output += MSG_UNNAMED$$165;
  output += '</option><option value="Pitcairn"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:260"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$166 = goog.getMsg('Pitcairn');
  output += MSG_UNNAMED$$166;
  output += '</option><option value="Poland"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:261"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$167 = goog.getMsg('Poland');
  output += MSG_UNNAMED$$167;
  output += '</option><option value="Portugal"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:262"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$168 = goog.getMsg('Portugal');
  output += MSG_UNNAMED$$168;
  output += '</option><option value="Puerto Rico"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:263"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$169 = goog.getMsg('Puerto Rico');
  output += MSG_UNNAMED$$169;
  output += '</option><option value="Qatar"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:264"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$170 = goog.getMsg('Qatar');
  output += MSG_UNNAMED$$170;
  output += '</option><option value="Reunion"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:265"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$171 = goog.getMsg('Reunion');
  output += MSG_UNNAMED$$171;
  output += '</option><option value="Romania"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:266"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$172 = goog.getMsg('Romania');
  output += MSG_UNNAMED$$172;
  output += '</option><option value="Russian Federation"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:267"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$173 = goog.getMsg('Russian Federation');
  output += MSG_UNNAMED$$173;
  output += '</option><option value="Rwanda"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:268"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$174 = goog.getMsg('Rwanda');
  output += MSG_UNNAMED$$174;
  output += '</option><option value="Saint Kitts and Nevis"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:269"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$175 = goog.getMsg('Saint Kitts and Nevis');
  output += MSG_UNNAMED$$175;
  output += '</option><option value="Saint Lucia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:270"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$176 = goog.getMsg('Saint Lucia');
  output += MSG_UNNAMED$$176;
  output += '</option><option value="Samoa"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:271"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$177 = goog.getMsg('Samoa');
  output += MSG_UNNAMED$$177;
  output += '</option><option value="San Marino"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:272"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$178 = goog.getMsg('San Marino');
  output += MSG_UNNAMED$$178;
  output += '</option><option value="Sao Tome and Principe"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:273"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$179 = goog.getMsg('Sao Tome and Principe');
  output += MSG_UNNAMED$$179;
  output += '</option><option value="Saudi Arabia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:274"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$180 = goog.getMsg('Saudi Arabia');
  output += MSG_UNNAMED$$180;
  output += '</option><option value="Senegal"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:275"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$181 = goog.getMsg('Senegal');
  output += MSG_UNNAMED$$181;
  output += '</option><option value="Seychelles"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:276"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$182 = goog.getMsg('Seychelles');
  output += MSG_UNNAMED$$182;
  output += '</option><option value="Sierra Leone"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:277"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$183 = goog.getMsg('Sierra Leone');
  output += MSG_UNNAMED$$183;
  output += '</option><option value="Singapore"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:278"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$184 = goog.getMsg('Singapore');
  output += MSG_UNNAMED$$184;
  output += '</option><option value="Slovakia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:279"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$185 = goog.getMsg('Slovakia');
  output += MSG_UNNAMED$$185;
  output += '</option><option value="Slovenia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:280"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$186 = goog.getMsg('Slovenia');
  output += MSG_UNNAMED$$186;
  output += '</option><option value="Solomon Islands"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:281"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$187 = goog.getMsg('Solomon Islands');
  output += MSG_UNNAMED$$187;
  output += '</option><option value="Somalia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:282"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$188 = goog.getMsg('Somalia');
  output += MSG_UNNAMED$$188;
  output += '</option><option value="South Africa"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:283"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$189 = goog.getMsg('South Africa');
  output += MSG_UNNAMED$$189;
  output += '</option><option value="Spain"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:284"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$190 = goog.getMsg('Spain');
  output += MSG_UNNAMED$$190;
  output += '</option><option value="Sri Lanka"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:285"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$191 = goog.getMsg('Sri Lanka');
  output += MSG_UNNAMED$$191;
  output += '</option><option value="St. Helena"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:286"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$192 = goog.getMsg('St. Helena');
  output += MSG_UNNAMED$$192;
  output += '</option><option value="St. Pierre and Miquelon"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:287"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$193 = goog.getMsg('St. Pierre and Miquelon');
  output += MSG_UNNAMED$$193;
  output += '</option><option value="Sudan"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:288"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$194 = goog.getMsg('Sudan');
  output += MSG_UNNAMED$$194;
  output += '</option><option value="Suriname"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:289"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$195 = goog.getMsg('Suriname');
  output += MSG_UNNAMED$$195;
  output += '</option><option value="Swaziland"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:290"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$196 = goog.getMsg('Swaziland');
  output += MSG_UNNAMED$$196;
  output += '</option><option value="Sweden"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:291"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$197 = goog.getMsg('Sweden');
  output += MSG_UNNAMED$$197;
  output += '</option><option value="Switzerland"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:292"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$198 = goog.getMsg('Switzerland');
  output += MSG_UNNAMED$$198;
  output += '</option><option value="Syrian Arab Republic"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:293"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$199 = goog.getMsg('Syrian Arab Republic');
  output += MSG_UNNAMED$$199;
  output += '</option><option value="Taiwan, Province of China"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:294"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$200 = goog.getMsg('Taiwan, Province of China');
  output += MSG_UNNAMED$$200;
  output += '</option><option value="Tajikistan"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:295"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$201 = goog.getMsg('Tajikistan');
  output += MSG_UNNAMED$$201;
  output += '</option><option value="Tanzania, United Republic of"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:296"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$202 = goog.getMsg('Tanzania, United Republic of');
  output += MSG_UNNAMED$$202;
  output += '</option><option value="Thailand"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:297"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$203 = goog.getMsg('Thailand');
  output += MSG_UNNAMED$$203;
  output += '</option><option value="Togo"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:298"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$204 = goog.getMsg('Togo');
  output += MSG_UNNAMED$$204;
  output += '</option><option value="Tokelau"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:299"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$205 = goog.getMsg('Tokelau');
  output += MSG_UNNAMED$$205;
  output += '</option><option value="Tonga"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:300"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$206 = goog.getMsg('Tonga');
  output += MSG_UNNAMED$$206;
  output += '</option><option value="Trinidad and Tobago"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:301"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$207 = goog.getMsg('Trinidad and Tobago');
  output += MSG_UNNAMED$$207;
  output += '</option><option value="Tunisia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:302"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$208 = goog.getMsg('Tunisia');
  output += MSG_UNNAMED$$208;
  output += '</option><option value="Turkey"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:303"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$209 = goog.getMsg('Turkey');
  output += MSG_UNNAMED$$209;
  output += '</option><option value="Turkmenistan"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:304"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$210 = goog.getMsg('Turkmenistan');
  output += MSG_UNNAMED$$210;
  output += '</option><option value="Turks and Caicos Islands"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:305"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$211 = goog.getMsg('Turks and Caicos Islands');
  output += MSG_UNNAMED$$211;
  output += '</option><option value="Tuvalu"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:306"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$212 = goog.getMsg('Tuvalu');
  output += MSG_UNNAMED$$212;
  output += '</option><option value="Uganda"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:307"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$213 = goog.getMsg('Uganda');
  output += MSG_UNNAMED$$213;
  output += '</option><option value="Ukraine"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:308"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$214 = goog.getMsg('Ukraine');
  output += MSG_UNNAMED$$214;
  output += '</option><option value="United Arab Emirates"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:309"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$215 = goog.getMsg('United Arab Emirates');
  output += MSG_UNNAMED$$215;
  output += '</option><option value="United Kingdom"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:310"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$216 = goog.getMsg('United Kingdom');
  output += MSG_UNNAMED$$216;
  output += '</option><option value="Uruguay"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:311"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$217 = goog.getMsg('Uruguay');
  output += MSG_UNNAMED$$217;
  output += '</option><option value="Uzbekistan"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:312"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$218 = goog.getMsg('Uzbekistan');
  output += MSG_UNNAMED$$218;
  output += '</option><option value="Vanuatu"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:313"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$219 = goog.getMsg('Vanuatu');
  output += MSG_UNNAMED$$219;
  output += '</option><option value="Vatican City State"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:314"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$220 = goog.getMsg('Vatican City State');
  output += MSG_UNNAMED$$220;
  output += '</option><option value="Venezuela"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:315"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$221 = goog.getMsg('Venezuela');
  output += MSG_UNNAMED$$221;
  output += '</option><option value="Viet Nam"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:316"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$222 = goog.getMsg('Viet Nam');
  output += MSG_UNNAMED$$222;
  output += '</option><option value="Virgin Islands (British)"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:317"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$223 = goog.getMsg('Virgin Islands (British)');
  output += MSG_UNNAMED$$223;
  output += '</option><option value="Virgin Islands (US)"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:318"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$224 = goog.getMsg('Virgin Islands (US)');
  output += MSG_UNNAMED$$224;
  output += '</option><option value="Wallis and Futuna"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:319"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$225 = goog.getMsg('Wallis and Futuna');
  output += MSG_UNNAMED$$225;
  output += '</option><option value="Serbia and Montenegro"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:320"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$226 = goog.getMsg('Serbia and Montenegro');
  output += MSG_UNNAMED$$226;
  output += '</option><option value="Yemen"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:321"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$227 = goog.getMsg('Yemen');
  output += MSG_UNNAMED$$227;
  output += '</option><option value="Congo, The Democratic Republic"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:322"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$228 = goog.getMsg('Congo, The Democratic Republic');
  output += MSG_UNNAMED$$228;
  output += '</option><option value="Zambia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:323"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$229 = goog.getMsg('Zambia');
  output += MSG_UNNAMED$$229;
  output += '</option><option value="Zimbabwe"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:324"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$230 = goog.getMsg('Zimbabwe');
  output += MSG_UNNAMED$$230;
  output += '</option><option value="Other-Not Shown"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:325"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$231 = goog.getMsg('Other-Not Shown');
  output += MSG_UNNAMED$$231;
  output += '</option><option value="Outlying Oceania"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:326"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$232 = goog.getMsg('Outlying Oceania');
  output += MSG_UNNAMED$$232;
  output += '</option><option value="Guernsey"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:327"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$233 = goog.getMsg('Guernsey');
  output += MSG_UNNAMED$$233;
  output += '</option><option value="Serbia"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:328"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$234 = goog.getMsg('Serbia');
  output += MSG_UNNAMED$$234;
  output += '</option><option value="Montenegro"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:329"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$235 = goog.getMsg('Montenegro');
  output += MSG_UNNAMED$$235;
  output += '</option><option value="Republic of Kosovo"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:330"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$236 = goog.getMsg('Republic of Kosovo');
  output += MSG_UNNAMED$$236;
  output += '</option><option value="Aland Islands"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:331"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$237 = goog.getMsg('Aland Islands');
  output += MSG_UNNAMED$$237;
  output += '</option><option value="Jersey"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:332"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$238 = goog.getMsg('Jersey');
  output += MSG_UNNAMED$$238;
  output += '</option><option value="Isle of Man"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:333"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$239 = goog.getMsg('Isle of Man');
  output += MSG_UNNAMED$$239;
  output += '</option><option value="Palestinian Territory"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:334"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$240 = goog.getMsg('Palestinian Territory');
  output += MSG_UNNAMED$$240;
  output += '</option><option value="St. Vincent And The Grenadines"' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="pstj.select.Countries templates/select.soy:335"' : '') + '>';
  /** @desc country name */
  var MSG_UNNAMED$$241 = goog.getMsg('St. Vincent And The Grenadines');
  output += MSG_UNNAMED$$241;
  output += '</option>';
  return soydata.VERY_UNSAFE.ordainSanitizedHtml(output);
};
if (goog.DEBUG) {
  pstj.select.Countries.soyTemplateName = 'pstj.select.Countries';
}
